version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-insurance-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password_123!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  ms-insurance:
    image: ms-insurance:latest
    container_name: ms-insurance-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MS-Insurance;User Id=sa;Password=Password_123!;TrustServerCertificate=True
    depends_on:
      - sqlserver

volumes:
  mssql-data:
