// <auto-generated />
using System;
using Infrastructure.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20260521002114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Adapters.Persistence.InsurancePolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceNumber")
                        .IsUnique();

                    b.ToTable("InsurancePolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ExpirationDate = new DateTime(2036, 5, 21, 0, 21, 14, 412, DateTimeKind.Utc).AddTicks(962),
                            InsuranceNumber = "INS-001",
                            IsActive = true,
                            PatientName = "Diego Rodríguez",
                            Plan = "Basic"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ExpirationDate = new DateTime(2031, 5, 21, 0, 21, 14, 412, DateTimeKind.Utc).AddTicks(979),
                            InsuranceNumber = "INS-BASIC-ACTIVE",
                            IsActive = true,
                            PatientName = "Juan Pérez",
                            Plan = "Basic"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ExpirationDate = new DateTime(2031, 5, 21, 0, 21, 14, 412, DateTimeKind.Utc).AddTicks(981),
                            InsuranceNumber = "INS-PREMIUM-ACTIVE",
                            IsActive = true,
                            PatientName = "Ana Gómez",
                            Plan = "Premium"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ExpirationDate = new DateTime(2031, 5, 21, 0, 21, 14, 412, DateTimeKind.Utc).AddTicks(984),
                            InsuranceNumber = "INS-ONCOLOGY-ACTIVE",
                            IsActive = true,
                            PatientName = "Carlos Ruiz",
                            Plan = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ExpirationDate = new DateTime(2028, 5, 21, 0, 21, 14, 412, DateTimeKind.Utc).AddTicks(985),
                            InsuranceNumber = "INS-INACTIVE",
                            IsActive = false,
                            PatientName = "María López",
                            Plan = "Premium"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ExpirationDate = new DateTime(2025, 5, 21, 0, 21, 14, 412, DateTimeKind.Utc).AddTicks(987),
                            InsuranceNumber = "INS-EXPIRED",
                            IsActive = true,
                            PatientName = "Luis Silva",
                            Plan = "Basic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
