// <auto-generated />
using System;
using Infrastructure.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    partial class InsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Adapters.Persistence.InsurancePolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceNumber")
                        .IsUnique();

                    b.ToTable("InsurancePolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            ExpirationDate = new DateTime(2036, 5, 24, 22, 7, 44, 251, DateTimeKind.Utc).AddTicks(252),
                            InsuranceNumber = "INS-001",
                            IsActive = true,
                            PatientName = "Diego Rodríguez",
                            Plan = "Basic"
                        },
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            ExpirationDate = new DateTime(2031, 5, 24, 22, 7, 44, 251, DateTimeKind.Utc).AddTicks(262),
                            InsuranceNumber = "INS-BASIC-ACTIVE",
                            IsActive = true,
                            PatientName = "Juan Pérez",
                            Plan = "Basic"
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"),
                            ExpirationDate = new DateTime(2031, 5, 24, 22, 7, 44, 251, DateTimeKind.Utc).AddTicks(265),
                            InsuranceNumber = "INS-PREMIUM-ACTIVE",
                            IsActive = true,
                            PatientName = "Ana Gómez",
                            Plan = "Premium"
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"),
                            ExpirationDate = new DateTime(2031, 5, 24, 22, 7, 44, 251, DateTimeKind.Utc).AddTicks(267),
                            InsuranceNumber = "INS-ONCOLOGY-ACTIVE",
                            IsActive = true,
                            PatientName = "Carlos Ruiz",
                            Plan = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a"),
                            ExpirationDate = new DateTime(2028, 5, 24, 22, 7, 44, 251, DateTimeKind.Utc).AddTicks(269),
                            InsuranceNumber = "INS-INACTIVE",
                            IsActive = false,
                            PatientName = "María López",
                            Plan = "Premium"
                        },
                        new
                        {
                            Id = new Guid("5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b"),
                            ExpirationDate = new DateTime(2025, 5, 24, 22, 7, 44, 251, DateTimeKind.Utc).AddTicks(271),
                            InsuranceNumber = "INS-EXPIRED",
                            IsActive = true,
                            PatientName = "Luis Silva",
                            Plan = "Basic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
